iris.features.required = CUSTOM_IMAGES SSBO


screen = TITLE \
         <empty> \
		 [PATHTRACING_OPTIONS] \
		 [DENOISING_OPTIONS]
screen.columns = 1

screen.PATHTRACING_OPTIONS = VOXEL_DIAMETER SAMPLE_COUNT \
						     MAX_BOUNCES    TARGET_BUFFER \
							 ENABLE_NEE     GI_SCALE
screen.PATHTRACING_OPTIONS.columns = 2

screen.DENOISING_OPTIONS = DENOISING ATROUS_ITERS
screen.DENOISING_OPTIONS.columns = 2

sliders = VOXEL_DIAMETER SAMPLE_COUNT MAX_BOUNCES GI_SCALE \
		  ATROUS_ITERS


clouds = off
sun = false
moon = false

separateAo = true
vignette = false

shadow.enabled = true
#// reversed creates issues with reflections
shadow.culling = false


#if VOXEL_DIAMETER == 128
	image.img_texbounds_xy = s_texbounds_xy RED_INTEGER R32UI UNSIGNED_INT true false 128 128 128
	image.img_texbounds_zw = s_texbounds_zw RED_INTEGER R32UI UNSIGNED_INT true false 128 128 128
	image.img_glcolor = s_glcolor RED_INTEGER R32UI UNSIGNED_INT true false 128 128 128
#elif VOXEL_DIAMETER == 64
	image.img_texbounds_xy = s_texbounds_xy RED_INTEGER R32UI UNSIGNED_INT true false 64 64 64
	image.img_texbounds_zw = s_texbounds_zw RED_INTEGER R32UI UNSIGNED_INT true false 64 64 64
	image.img_glcolor = s_glcolor RED_INTEGER R32UI UNSIGNED_INT true false 64 64 64
#elif VOXEL_DIAMETER == 32
	image.img_texbounds_xy = s_texbounds_xy RED_INTEGER R32UI UNSIGNED_INT true false 32 32 32
	image.img_texbounds_zw = s_texbounds_zw RED_INTEGER R32UI UNSIGNED_INT true false 32 32 32
	image.img_glcolor = s_glcolor RED_INTEGER R32UI UNSIGNED_INT true false 32 32 32
#elif VOXEL_DIAMETER == 16
	image.img_texbounds_xy = s_texbounds_xy RED_INTEGER R32UI UNSIGNED_INT true false 16 16 16
	image.img_texbounds_zw = s_texbounds_zw RED_INTEGER R32UI UNSIGNED_INT true false 16 16 16
	image.img_glcolor = s_glcolor RED_INTEGER R32UI UNSIGNED_INT true false 16 16 16
#endif


texture.composite.colortex4 = minecraft:textures/atlas/blocks.png
texture.composite.colortex14 = minecraft:textures/atlas/blocks_s.png


#// Screen-size SSBOs are Iris 1.6.6+
bufferObject.0 = 4 true GI_SCALE GI_SCALE

size.buffer.colortex5 = GI_SCALE GI_SCALE
size.buffer.colortex6 = GI_SCALE GI_SCALE
size.buffer.colortex7 = GI_SCALE GI_SCALE
size.buffer.colortex8 = GI_SCALE GI_SCALE
size.buffer.colortex9 = GI_SCALE GI_SCALE
size.buffer.colortex10 = GI_SCALE GI_SCALE
size.buffer.colortex11 = GI_SCALE GI_SCALE

uniform.vec2.gi_resolution = vec2(viewWidth * GI_SCALE, viewHeight * GI_SCALE)